# Generated by Django 3.2.25 on 2025-01-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='student_photos',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='face_images',
            field=models.JSONField(default=list),
        ),
    ]
